### PR TITLE
[major] fix config.yaml naming consistency

### LINKED ISSUE #37: config `AthenzRootCA` is not used
as title.
https://github.com/yahoojapan/authorization-proxy/search?q=AthenzRootCA&unscoped_q=AthenzRootCA

## TODO
1. create HTTP client by `AthenzRootCA`
1. add HTTP client option in https://github.com/yahoojapan/athenz-authorizer/blob/master/option.go
1. update the authorizer creation logic accordingly

### LINKED ISSUE #44: configuration name is not consistency
Configuration name should be `_` separated or by letter case?

https://github.com/yahoojapan/authorization-proxy/blob/1360c02583f954790106fb51f367723d4d034239/config/config.go#L63

https://github.com/yahoojapan/authorization-proxy/blob/1360c02583f954790106fb51f367723d4d034239/config/config.go#L137

### PR DESCRIPTION
**Pull request by WindzCUHK**
# Description

## TODO
1. [x] update config yaml to `v2.0.0`
1. [x] update go.mod (depends on: https://github.com/yahoojapan/athenz-authorizer/pull/69)

## changes
1. fix multiple naming consistency problem in `config.go`.
2. remove role token force enable
3. config version to `v2.0.0`
4. move unit test data to `/test/data`
5. add log level support
6. fix lint: `SA1019: t.BuildNameToCertificate is deprecated: NameToCertificate only allows associating a single certificate with a given name. Leave that field nil to let the library select the first compatible chain from Certificates.  (staticcheck)`
7. handle timeout and ca in config.Athenz

https://github.com/yahoojapan/authorization-proxy/blob/20ac59579566b5b19719f6b043ca962762c99819/test/data/example_config.yaml#L1-L69

### Details
Suggested naming convention rules:
1. using `camelCase` in yaml
1. type: duration
    1. must contain `duration` in the comment
    1. must end with noun that has the meaning "time range"
        1. ✅ `expiry`, `period`, `delay`, `duration`
        1. ❌ `time`
1. type: boolean
    1. **NO** `enable` prefix
1. type: array
    1. **ADD** `s` suffix

#### Remarks
1. log level
    1. https://github.com/kpango/glg/blob/f87edaada63804d40fdf6f951b87690d3971e266/glg.go#L205-L262
    1. https://github.com/kpango/glg/blob/f87edaada63804d40fdf6f951b87690d3971e266/glg.go#L78-L95
1. About [ETag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag), People use `ETag`, `Etag` and `etag` in docs.
	1. golang use `ETag` as constant
		- https://github.com/go-http-utils/headers/blob/fed159eddc2adec07fb6fc214160acf53280ac49/headers.go#L56
	1. S3 using `ETag` as constant
		- https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#CompleteMultipartUploadOutput.SetETag
1. https://kubernetes.io/docs/contribute/style/style-guide/#avoid-latin-phrases
1. https://cloud.google.com/apis/design/naming_convention#time_and_duration
    1. using long form `duration`

## Type of change

- [x] New feature
- [x] Bug fix
- [x] Refactoring (no functional changes, no api changes)

### Flags

- [x] breaks backward compatibility
- [x] requires a documentation update

## Related issue/PR

- Fixes #37, #44
- Closes #35 

---

## Checklist

- [x] Followed the guidelines in the CONTRIBUTING document
- [x] Added prefix `[major]`/`[minor]`/`[patch]`/`[skip]` in the PR title
- [x] Tested and linted the code
- [x] Commented the code
- [x] Made corresponding changes to the documentation
- [x] Confirmed no dropping in test coverage (by [Codecov](https://codecov.io/gh/yahoojapan/authorization-proxy/pulls))
- [x] Passed all pipeline checking
- [x] Approved by >1 reviewer

## Checklist for maintainer
- [ ] Use `Squash and merge`
- [ ] Double-confirm the merge message has prefix `[major]`/`[minor]`/`[patch]`/`[skip]`
- [ ] Delete the branch after merge

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -227,15 +254,15 @@ func New(path string) (*Config, error) {
 	if err != nil {
 		return nil, errors.Wrap(err, "decode file failed")
 	}
-	// roletoken must be enabled by default.
+	// roletoken must be enable by default.
 	// so, force enable here.
 	// if we default to access token, we will change it here.
 	cfg.Authorization.Role.Enable = true
```
Comment (ssunorz) [inline config/config.go:260]:
```suggestion
	cfg.Authorization.RoleToken.Enable = true
```

**Comment by tatyano** [comment]
@WindzCUHK 
(Perhaps out of the scope of this ticket, but) It's better to add a filed to allow configuration to change from `Authorization: Bearer` like other headers.(Although using another header name than `Authorization: Bearer` is against the standard.)
https://github.com/yahoojapan/authorization-proxy/blob/745655002bae0ca52b8ab8a0d937691332019aff/config/config.go#L214-L233

File: config/config.go [hunk 2]
```diff
@@ -25,195 +25,230 @@ import (
...
 
-// DebugServer represents the server for debug use.
-type DebugServer struct {
-	// Enable represents if user want to enable debug server functionality.
-	Enable bool `yaml:"enable"`
-
-	// Port represents debug server port.
-	Port int `yaml:"port"`
+	// Header represents the HTTP header name for extracting the role token.
+	Header string `yaml:"header"`
```
[the remark this answers is not in the document]
Comment (WindzCUHK) [reply config/config.go]: Thought that is for client sidecar only, but it is better to make them match.

fixed in https://github.com/yahoojapan/authorization-proxy/pull/64/commits/502566f4afe4fb99b21a42c091cf135c8f07ce28

**Comment by WindzCUHK** [comment]
@tatyano
> It's better to add a filed to allow configuration to change from Authorization: Bearer like other headers.

created an issue: https://github.com/yahoojapan/athenz-authorizer/issues/68

File: config/config.go [hunk 3]
```diff
@@ -25,195 +25,230 @@ import (
...
+	BufferSize uint64 `yaml:"bufferSize"`
 
-	// BypassURLPaths represent URL paths that require authorization bypassing.
-	// WARNING!!! Setting this configuration may introduce security hole in your system. Do NOT set this configuration with URL paths other than application's healthcheck endpoint.
-	// Tips for performance: define your healthcheck endpoint with different lenght from the most frequestly used endpoint, e.g. `/most_used` (len: 10) with `/healthcheck` (len: 12), instead of `/healthccc` (len: 10)
-	BypassURLPaths []string `yaml:"bypass_url_paths"`
+	// BypassURLPaths represents URL paths that require to bypass authorization.
+	// WARNING!!! Setting this configuration may introduce security hole in your system. ONLY set this configuration as the application's health check endpoint.
+	// Tips for performance: define your health check endpoint with a different length from the most frequestly used endpoint, for example, use `/healthcheck` (len: 12) when `/most_used` (len: 10), instead of `/healthccc` (len: 10)
+	BypassURLPaths []string `yaml:"bypassUrlPaths"`
```
Comment (tatyano) [inline config/config.go:145]: @WindzCUHK Since this functionality is not intended to be used for bypassing the authn/authz, `HealchCheckPaths` is more preferred.

File: config/config.go [hunk 4]
```diff
@@ -25,195 +25,230 @@ import (
...
 
-	// PubKeyEtagExpTime represents the Etag cache expiration time of Athenz PubKey.
-	PubKeyEtagExpTime string `yaml:"pubKeyEtagExpTime"`
+	// Policy represents the configuration to fetch Athenz policies.
+	Policy Policy `yaml:"policy"`
 
-	// PubKeyEtagFlushDur represent the Etag cache expiration check duration.
-	PubKeyEtagFlushDur string `yaml:"pubKeyEtagFlushDur"`
+	// JKWS represents the configuration to fetch Athenz JKWS.
+	JKWS JKWS `yaml:"jwks"`
```
Comment (kyfujisa) [inline config/config.go:160]: Are you intending to `JWK`?
Also, since token is singular, I thought `jwk` would be fine, but why do you use `jwks`? 
```suggestion
	JWKS JWKS `yaml:"jwks"`
```

Comment (WindzCUHK) [reply config/config.go:160]: It refers to `JSON Web Key Sets`. https://tools.ietf.org/html/rfc7517#appendix-A
But, seems `jwk` is simpler.

File: config/config.go (hunk 3 above)
Comment (WindzCUHK) [reply config/config.go:145]: Seems it is under `proxy:`, should it be `AppHealthCheckPaths`/`OriginHealthCheckPaths`?
Or, move the config under `authorization:`?

File: config/config.go (hunk 4 above)
Comment (kyfujisa) [reply config/config.go]: > JSON Web Key Sets

You didn't mean plural, thank you.

File: config/config.go (hunk 3 above)
Comment (WindzCUHK) [reply config/config.go:145]: @tatyano

Comment (WindzCUHK) [reply config/config.go:145]: @tatyano Any idea on the new name?

File: config/config_test.go [hunk 5]
```diff
@@ -41,7 +41,7 @@ func TestNew(t *testing.T) {
 		{
 			name: "Test file content not valid",
 			args: args{
-				path: "./testdata/not_valid_config.yaml",
+				path: "../test/data//not_valid_config.yaml",
```
Comment (kevindiu) [inline config/config_test.go:44]:
```suggestion
				path: "../test/data/not_valid_config.yaml",
```

Comment (WindzCUHK) [reply config/config_test.go]: fixed: 8e56253

File: docs/debug.md [hunk 6]
```diff
@@ -16,16 +16,16 @@
...
+  debug:
     enable: true
     port: 6083
-    enable_dump: true
+    dump: true
 ...
 ```
 
-The example configuration file is [here](../config/testdata/example_config.yaml). For more information, please refer to [config.go](./config/config.go).
+The example configuration file is [here](../config/test/data/example_config.yaml). For more information, please refer to [config.go](./config/config.go).
```
Comment (ssunorz) [inline docs/debug.md:28]:
```suggestion
The example configuration file is [here](../test/data/example_config.yaml). For more information, please refer to [config.go](../config/config.go).
```

File: docs/debug.md [hunk 7]
```diff
@@ -85,4 +85,4 @@ server:
...
```
Comment (ssunorz) [inline docs/debug.md:88]: same as above

**Comment by ssunorz** [comment]
It looks like there's something in this file that needs to be fixed.

https://github.com/yahoojapan/authorization-proxy/blob/44035804e0ec9e1b8c8f5777736bdc7db6baaaae/k8s/gen.sh

File: config/config.go (hunk 3 above)
Comment (tatyano) [reply config/config.go:145]: @WindzCUHK I think `OriginHealthCheckPaths` looks good. `AppHealthCheckPaths` does not really tell what is `App`. Moving it under `authorization:` is optional for me.

File: service/server.go [hunk 8]
```diff
@@ -337,9 +337,9 @@ func (s *server) listenAndServeAPI() error {
 }
 
 func (s *server) healthzSrvEnable() bool {
```
Comment (ssunorz) [inline service/server.go:339]: Since the `HealthzPort` has been changed, I think this name should be changed as well.
What about `healthCheckSrvEnable()`, etc.

Comment (WindzCUHK) [reply service/server.go]: fixed in: 41e9d6b
use short form `hcSrvEnable` for private methods

File: config/config.go (hunk 1 above)
Comment (WindzCUHK) [reply config/config.go]: removed in latest code

File: config/config.go (hunk 3 above)
Comment (WindzCUHK) [reply config/config.go]: fixed in: 25c83be

File: docs/debug.md (hunk 7 above)
Comment (WindzCUHK) [reply docs/debug.md]: fixed in: 86fbb6a0eee66c10179c42c8cff2434e2f9715ee

File: docs/debug.md (hunk 6 above)
Comment (WindzCUHK) [reply docs/debug.md]: fixed in: 86fbb6a0eee66c10179c42c8cff2434e2f9715ee

**Comment by WindzCUHK** [comment]
> It looks like there's something in this file that needs to be fixed.
> 
> https://github.com/yahoojapan/authorization-proxy/blob/44035804e0ec9e1b8c8f5777736bdc7db6baaaae/k8s/gen.sh

fixed in: 19004f9
